# Generated by Django 5.0.6 on 2024-08-25 04:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('message', models.CharField(max_length=999999999999999999999999999999999999999999999999999999999999999999999999999999999999999)),
                ('user', models.CharField(max_length=100)),
                ('review_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokensModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=999999999999)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('refCode', models.CharField(default='', max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=240)),
                ('last_name', models.CharField(max_length=240)),
                ('email', models.EmailField(db_index=True, max_length=240, unique=True)),
                ('username', models.CharField(max_length=240, unique=True)),
                ('referred_by', models.CharField(blank=True, max_length=240)),
                ('referral_code', models.CharField(blank=True, max_length=240)),
                ('referrals', models.PositiveIntegerField(blank=True, default=0)),
                ('indirectReferrals', models.PositiveIntegerField(blank=True, default=0)),
                ('referral_code_expired', models.BooleanField(blank=True, default=False)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('direct_referrals', models.CharField(blank=True, default='', max_length=99999)),
                ('indirect_referrals', models.CharField(blank=True, default='', max_length=99999)),
                ('non_pro_referrals', models.CharField(blank=True, default='', max_length=99999)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('notification', models.CharField(max_length=999999999999999999999999999999999999999999999999999999999999999999999999999999999999999)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('action_required', models.BooleanField(default=False)),
                ('action', models.CharField(default='', max_length=100)),
                ('actionID', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
