# Generated by Django 5.1.2 on 2024-11-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0002_customusermodel_total_points_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notificationType',
            field=models.CharField(default='', max_length=100),
        ),
    ]
