# Generated by Django 5.0.6 on 2024-07-10 17:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0002_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
