# Generated by Django 5.0.6 on 2024-07-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0003_notifications_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='action_required',
            field=models.BooleanField(default=False),
        ),
    ]
