# Generated by Django 5.0.6 on 2024-07-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0004_notifications_action_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='action',
            field=models.CharField(default='', max_length=100),
        ),
    ]
