# Generated by Django 5.0.6 on 2024-07-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0005_notifications_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='actionID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
