# Generated by Django 5.1.2 on 2024-11-22 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0006_alter_customusermodel_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
