# Generated by Django 5.0.6 on 2024-07-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0006_notifications_actionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='dev_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
