# Generated by Django 5.1.2 on 2024-11-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0007_customusermodel_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
