# Generated by Django 5.0.6 on 2024-07-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0007_customusermodel_dev_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='dev_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
