# Generated by Django 5.0.6 on 2024-07-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0008_alter_customusermodel_dev_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='dev_type',
        ),
    ]
