# Generated by Django 5.0.6 on 2024-07-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0010_reviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='review_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
