# Generated by Django 5.1.2 on 2024-11-03 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('categoryImg', models.FileField(blank=True, null=True, upload_to='categoryImg/')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uID', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('question', models.CharField(max_length=99999999999999999999999999999999999999, unique=True)),
                ('correct_answer', models.CharField(max_length=999999999999999999999)),
                ('incorrect_answers', models.CharField(max_length=999999999999999999999999999999)),
                ('aurthor', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionSystem.questionscategory')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionSystem.questionlevel')),
            ],
        ),
        migrations.CreateModel(
            name='QuizPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256)),
                ('level', models.CharField(max_length=256)),
                ('limit', models.CharField(max_length=256)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
