# Generated by Django 5.1.2 on 2024-10-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionscategory',
            name='categoryImg',
            field=models.FileField(blank=True, null=True, upload_to='categoryImg/'),
        ),
    ]
