# Generated by Django 5.1.2 on 2024-11-03 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=8, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreNewRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uID', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('new_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_new_ref', to=settings.AUTH_USER_MODEL)),
                ('ref_king', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_king', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
