# Generated by Django 5.0.6 on 2024-07-02 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralSystem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreNewRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_new_ref', to=settings.AUTH_USER_MODEL)),
                ('ref_king', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_king', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
