# Generated by Django 5.0.6 on 2024-07-12 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralSystem', '0002_storenewref'),
    ]

    operations = [
        migrations.AddField(
            model_name='storenewref',
            name='uID',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
