# Generated by Django 5.1.2 on 2024-11-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralSystem', '0002_referralmodelhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralmodelhistory',
            name='no_of_referrals',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
