# Generated by Django 5.1.2 on 2024-11-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralSystem', '0003_referralmodelhistory_no_of_referrals'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralmodelhistory',
            name='month',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
    ]
