# Generated by Django 5.1.2 on 2024-11-03 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclinedTransferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('requestedBy', models.CharField(max_length=100)),
                ('attendedBy', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=999999999999999999)),
                ('amountRequested', models.CharField(max_length=100)),
                ('requestedBy_balance', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IssueWithdrawModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('issuer', models.CharField(default='', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methods', models.CharField(choices=[('mobile_money', 'Mobile Money')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transferID', models.CharField(max_length=20)),
                ('transferReference', models.CharField(max_length=100)),
                ('transferCode', models.CharField(max_length=100)),
                ('recipientID', models.CharField(max_length=20)),
                ('sender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=240)),
                ('paymentMethod', models.CharField(choices=[('mobile_money', 'Mobile Money')], default='mobile_money', max_length=20)),
                ('paymentMethodName', models.CharField(blank=True, max_length=100)),
                ('accountNumber', models.CharField(max_length=15)),
                ('carrier', models.CharField(max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecieptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('recieptID', models.CharField(max_length=50)),
                ('recieptCode', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StorePaymentProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('amount', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('contact', models.CharField(max_length=256)),
                ('payment_type', models.CharField(max_length=256)),
                ('carrier_code', models.CharField(max_length=50)),
                ('carrier_name', models.CharField(max_length=50)),
                ('date_of_payment', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transactionType', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=10)),
                ('transactionTypeStatus', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('transactionRefrence', models.CharField(default=None, max_length=30)),
                ('paymentMethod', models.CharField(max_length=20)),
                ('mobileNumber', models.CharField(max_length=15)),
                ('carrier', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentSystem.accountmodel')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrwalSheetsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('sheet', models.FileField(upload_to='excel_withdrwal_list/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('completedTransfers', models.BooleanField(default=False)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
