# Generated by Django 5.1.2 on 2024-11-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
