# Generated by Django 5.1.2 on 2024-11-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0002_accountmodel_total_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuewithdrawmodel',
            name='acN',
            field=models.CharField(default='', max_length=50),
        ),
    ]
