# Generated by Django 5.0.6 on 2024-08-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0003_recieptmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieptmodel',
            name='recieptCode',
            field=models.CharField(default='', max_length=50),
        ),
    ]
