# Generated by Django 5.0.6 on 2024-08-03 20:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0005_alter_recieptmodel_recieptcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transferID', models.CharField(max_length=20)),
                ('transferReference', models.CharField(max_length=100)),
                ('transferCode', models.CharField(max_length=100)),
                ('recipientID', models.CharField(max_length=20)),
                ('sender', models.CharField(max_length=20)),
            ],
        ),
    ]
