# Generated by Django 5.0.6 on 2024-08-03 21:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0006_transfermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclinedTransferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('requestedBy', models.CharField(max_length=100)),
                ('attendedBy', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=999999999999999999)),
                ('amountRequested', models.CharField(max_length=100)),
                ('requestedBy_balance', models.CharField(max_length=100)),
            ],
        ),
    ]
