# Generated by Django 5.0.6 on 2024-08-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0008_withdrwalsheetsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrwalsheetsmodel',
            name='completedTransfers',
            field=models.BooleanField(default=False),
        ),
    ]
