# Generated by Django 5.1.2 on 2024-11-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0010_storepaymentprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepaymentprocess',
            name='carrier_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storepaymentprocess',
            name='carrier_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
