# Generated by Django 5.1.2 on 2024-11-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindeveloperstatusmodel',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
