# Generated by Django 5.0.6 on 2024-07-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSystem', '0002_walletmodel_date_walletmodel_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmodel',
            name='month',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
