# Generated by Django 5.0.6 on 2024-09-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminSystem', '0002_user_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_wallet',
        ),
    ]
