# Generated by Django 5.1.4 on 2024-12-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSystem', '0002_alter_admindeveloperstatusmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer_wallet',
            name='month',
            field=models.IntegerField(default=12),
        ),
    ]
