# Generated by Django 5.0.6 on 2024-07-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminSystem', '0003_alter_walletmodel_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletmodel',
            old_name='month',
            new_name='wallet_name',
        ),
    ]
