# Generated by Django 5.0.6 on 2024-07-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSystem', '0005_admindeveloperstatusmodel_admindeveloperusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindeveloperusermodel',
            name='approved_status',
            field=models.BooleanField(default=False),
        ),
    ]
