# Generated by Django 5.1.2 on 2024-10-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSystem', '0007_developer_wallet_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer_wallet',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='developer_wallet',
            name='month',
            field=models.IntegerField(default=10),
        ),
    ]
