# Generated by Django 5.0.6 on 2024-09-18 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminSystem', '0007_developer_wallet_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer_wallet',
            name='total_amount',
        ),
    ]
