# Generated by Django 5.1.2 on 2024-11-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSystem', '0008_remove_developer_wallet_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer_wallet',
            name='month',
            field=models.IntegerField(default=11),
        ),
    ]
