# Generated by Django 5.0.6 on 2024-09-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSystem', '0009_otp_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp_storage',
            name='email',
        ),
        migrations.AddField(
            model_name='otp_storage',
            name='dev_joining',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='otp_storage',
            name='dev_verifying',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
