# Generated by Django 5.0.6 on 2024-09-22 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSystem', '0010_remove_otp_storage_email_otp_storage_dev_joining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_storage',
            name='dev_joining',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joining_otps', to='adminSystem.admindeveloperusermodel'),
        ),
        migrations.AlterField(
            model_name='otp_storage',
            name='dev_verifying',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifying_otps', to='adminSystem.admindeveloperusermodel'),
        ),
    ]
