# Generated by Django 5.0.6 on 2024-09-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSystem', '0011_alter_otp_storage_dev_joining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_storage',
            name='dev_verifying',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
