# Generated by Django 5.0.6 on 2024-09-22 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSystem', '0012_alter_otp_storage_dev_verifying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_storage',
            name='dev_joining',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joining_otps', to='adminSystem.admindeveloperusermodel'),
        ),
    ]
