# Generated by Django 5.0.6 on 2024-09-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminSystem', '0014_alter_otp_storage_dev_joining'),
    ]

    operations = [
        migrations.DeleteModel(
            name='otp_storage',
        ),
    ]
